name: Build
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!dev'      # excludes dev
      - '!master'   # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Use yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Lint code
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
